---
id: greetings
version: '1.0'
name: Hello Person
start: NewOrder
functions:
- name: orderNew
  type: custom
  operation: "rest:post:/"
states:
- name: NewOrder
  type: operation
  actions:
  - functionRef: orderNew
  end: true